export const CHANGE_INPUT_VALUE = "change_input_value"
export const ADD_TODO_ITEM = "add_todo_item"
export const ADD_DONE_ITEM = "add_done_item"
export const DELETE_TODO_ITEM = "delete_todo_item"
export const CHANGE_SWITCH_TITLE = "change_switch_title"